on: push
name: Auto Deploy
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@master
      env:
        FTP_SERVER: ftp.digitalcombo.com.br/wp-content/plugins/digital-combo-pay/
        FTP_USERNAME: homologacao@homologacao.digitalcombo.com.br
        FTP_PASSWORD: ${{ secrets.FTP_PASS }}
        #ARGS: --delete
